# Generated by Django 2.2.6 on 2019-10-21 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 1, 44, 45, 755834), verbose_name='Creation Date')),
            ],
            options={
                'db_table': 'cuisineType',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealType', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 1, 44, 45, 730857), verbose_name='Creation Date')),
            ],
            options={
                'db_table': 'mealTypes',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('menuImage', models.CharField(max_length=300, verbose_name='Menu Image')),
                ('vegetarian', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 1, 44, 45, 756335), verbose_name='Creation Date')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcart.CuisineType')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 1, 44, 45, 755335), verbose_name='Creation Date')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='MenuRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 1, 44, 45, 757840), verbose_name='Creation Date')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcart.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_ratings',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.TextField(default='', verbose_name='Street Address')),
                ('aptSuite', models.TextField(default='', verbose_name='Apt/Suite, Floor')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('zipCode', models.CharField(default='', max_length=6, verbose_name='Zip code')),
                ('phoneNumber', models.CharField(default='', max_length=10, verbose_name='Zip code')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 1, 44, 45, 756839), verbose_name='Creation Date')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcart.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
