# Generated by Django 2.2.6 on 2019-10-21 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcart', '0002_auto_20191022_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 9, 31, 609128), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='cuisinetype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 9, 31, 607623), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 9, 31, 605619), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 9, 31, 608125), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuImage',
            field=models.ImageField(upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='menurating',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 9, 31, 610131), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 9, 31, 606621), verbose_name='Creation Date'),
        ),
    ]
