# Generated by Django 2.2.6 on 2019-10-21 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcart', '0003_auto_20191022_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 27, 20, 691093), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='cuisinetype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 27, 20, 689086), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 27, 20, 688084), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 27, 20, 690089), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='menurating',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 27, 20, 692095), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 27, 20, 688585), verbose_name='Creation Date'),
        ),
    ]
