# Generated by Django 2.2.6 on 2019-10-21 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcart', '0004_auto_20191022_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 28, 53, 601519), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='cuisinetype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 28, 53, 600017), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 28, 53, 599015), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 28, 53, 601018), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='menurating',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 28, 53, 602020), verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 2, 28, 53, 599516), verbose_name='Creation Date'),
        ),
    ]
